Fixed missing downloads
ain/docker-httpd pull request #2
Opened 2017-01-25 23:28 UTC by AndreasPrang

Fixed the missing downloads and broken dependencies.

2017-01-26 00:11 UTC, ain commented on 5.1.3/Dockerfile
> +RUN cd /tmp && wget http://download.savannah.gnu.org/releases/freetype/freetype-2.6.tar.gz \
Thanks for a fix!

2017-01-26 00:18 UTC, ain requested changes

2017-01-26 00:18 UTC, ain commented on 5.1.3/httpd.conf
> +# In particular, see
Let's not change `httpd.conf` as it'd break legacy apps that are based on this image. 

If anyone needs a change on this, they can mount in their own (or extend).

2017-01-26 00:18 UTC, ain commented on 5.1.3/Dockerfile
> +RUN echo "FromLineOverride=YES" >> /etc/ssmtp/ssmtp.conf
Same here, let's keep the symlink for legacy purposes. Please also retain EOL.

2017-01-26 08:31 UTC, AndreasPrang commented on 5.1.3/httpd.conf
> +# In particular, see
When I tried to run the Image, the apache2 2.2.32 won't start with the old `http.conf`.

2017-01-26 08:32 UTC, AndreasPrang commented on 5.1.3/Dockerfile
> +RUN echo "FromLineOverride=YES" >> /etc/ssmtp/ssmtp.conf
OK. lets keep the symlink.

2017-01-27 01:34 UTC, ain commented on 5.1.3/httpd.conf
> +# In particular, see
I see. Thanks for feedback on this, I'll take a second look into it and confirm.

2019-11-03 11:04 UTC, ain commented
Closing. Dockerfile compilaton fails over `wheezy` dependencies. Complete revamp required.

2019-11-03 11:04 UTC, closed without merging